LogFilePath: ../go_discord_gpt_logs
maxFetchRecord: 100
maxUserRecord: 50
clearCmd: clear chat history
clearCmdDesc: Clear the conversation context with ${botName}.
clearDelimiter: (The chat history between you and the robot has been cleared.)
model: gpt-3.5-turbo
temperature: 0.8
prompt: You are a helpful assistant.
freeChatLimit: 50
onConversation: true
onAt: true